@startuml
interface Identifiable {
   +getId() : UUID
}

abstract Neo4jEntityBase

class AuthnIdentity {
    -foreignUserId: UUID
}

class Settings {
    +displayName?: String
}

User -|> Identifiable

User "1" *--> "1" AuthnIdentity
User "1" *--> "1" Settings
@enduml
