@startuml
!$BGCOLOR = transparent
!include ./puml-theme-cyborg-outline.puml


interface Identifiable {
   +getId() : UUID
}

abstract JPAEntityBase

class AuthnIdentity {
    -foreignUserId: UUID
}

JPAEntityBase -|> Identifiable
User -|> JPAEntityBase

User "1" *--> "1" AuthnIdentity
User "1" *--> "1" Settings

@enduml
